== Build Docker Images for CentOS with SSH and SSR for arukas
=== If you have any questions ,please mail to elsesky@elsesky.bid
=== Description
---------------------------------------------------------------------------------
Open port 22 for SSH,you can set root password use -r in CMD
Open port from 8388 to 8406 for ssr,you can set port password use -p in CMD
You can set 8388-8406 in Port option for ssr and 22 in Port option for ssh on arukas.
---------------------------------------------------------------------------------


=== USAGE
===== PORT:
-------
22:SSH
-------
----
8388 - 8406:SSR
----

==== CMD:
```
-r root_pass -p port_pass -o OBFS -m METHOD -P PROTOCOL
```

EXAMPLE1[compatible with SS]:
----
-r password -p password -o plain -m aes-256-cfb -P origin
----
EXAMPLE2[SSR only]:
-----
-r password -p password -o tls1.2_ticket_auth_compatible -m aes-256-cfb -P auth_aes128_md5
-----
==== CMD(ADVANCE):
By default ,port pass will be set by -p arg.You  can set password per port. From port 8338 to 8406, use arg p1 to p19 to set,port-pass table is below:
--------
8388:p1
8389:p2
8390:p3
8391:p4
8392:p5
8393:p6
8394:p7
8395:p8
8396:p9
8397:p10
8398:p11
8399:p12
8400:p13
8401:p14
8402:p15
8403:p16
8404:p17
8405:p18
8406:p19
--------
EXAMPLE1[compatible with SS](set port 8388,8389,8400):
-------
-r password -p password -o plain -m aes-256-cfb -P origin --p1 p1password --p2 p2password --p13 p13password
-------

EXAMPLE2[SSR only](set port 8388,8389,8401):
---------
-r password -p password -o tls1.2_ticket_auth_compatible -m aes-256-cfb -P auth_aes128_md5  --p1 p1password --p2 p2password --p14 p14password
---------
NOTICE! You must use -p to set port pass before you use --p1 to --p19 to set per port,or the port pass will be reset by -p arg

=== If you run without any one param above,it use default value below

-r default value: 
-----------------------------
password
-----------------------------

-p default value:
-----------------------------
password
-----------------------------

-o default value:
-----------------------------
tls1.2_ticket_auth_compatible
-----------------------------

-m default value:
-----------------------------
aes-256-cfb
-----------------------------

-P default value:
-----------------------------
auth_aes128_md5
-----------------------------

-p1 to -p19 default value:
-----------------------------
password
-----------------------------
(Notice! if you use -p arg before --p1 to --p19 arg to set port pass, the default value will be reset by -p arg)
